### ISSUE TITLE
Add Urm's Custom Cell Lighting and Water

### ISSUE THREAD

**Issue by magicaldave** [DreamWeave-MP/Dreamweave#33]
![Image](https://github.com/DreamWeave-MP/Dreamweave/assets/2161150/0ef27eeb-fed3-410e-b775-7f5b1a2f8a35)

**Comment by magicaldave** [comment]
https://github.com/DreamWeave-MP/Dreamweave/pull/27

https://github.com/DreamWeave-MP/CoreScripts/pull/23

with the addition of the `fog` table into config.lua, this MR will be complete and ready for review. All other functionality related to it has been tested and seems to work.

Without #28 , though, the utility of it is limited.

**Comment by HotaruBlaze** [comment]
#27, https://github.com/DreamWeave-MP/CoreScripts/pull/23, and #28 all good good to me, approved each one

**Comment by magicaldave** [comment]
This issue is almost resolved but coreScripts still doesn't assign the values in the fog table when assigning them to a new cell.
