### ISSUE TITLE
Hand-to-Hand has no effect in PVP

### ISSUE THREAD

**Issue by magicaldave** [DreamWeave-MP/Dreamweave#37]
Two players attacking each other with hand to hand will not trigger fatigue changes on the hit actor.

**Comment by HotaruBlaze** [comment]
This works as intended on Vermillion, for multiple players they take fatigue damage as normal, the only oddity is the bar only reflects their HP not their fatigue

**Comment by magicaldave** [comment]
Closing as a false positive.
